export const CARGANDO = 'CARGANDO';
export const EDIT_RESPUESTAS = 'EDIT_RESPUESTAS';
export const REMOVE_RESPUESTAS = 'REMOVE_RESPUESTAS';

export const EDIT_PREGUNTA = 'EDIT_PREGUNTA';
export const REMOVE_PREGUNTA = 'REMOVE_PREGUNTA';
